INSERT INTO [dbo].[mtPermission] ([description] ,[display] ,[seq] ,[sub_seq])
VALUES ('general-select2admin','SELECT2_ADMIN',99,110)

INSERT INTO [dbo].[mtPermission] ([description] ,[display] ,[seq] ,[sub_seq])
VALUES ('admin-index','ADMIN_PAGE',100,100)
INSERT INTO [dbo].[mtPermission] ([description] ,[display] ,[seq] ,[sub_seq])
VALUES ('admin-admin_read','ADMIN_LIST',100,110)
INSERT INTO [dbo].[mtPermission] ([description] ,[display] ,[seq] ,[sub_seq])
VALUES ('admin-add','ADMIN_ADD',100,111)
INSERT INTO [dbo].[mtPermission] ([description] ,[display] ,[seq] ,[sub_seq])
VALUES ('admin-update','ADMIN_UPDATE',100,112)

INSERT INTO [dbo].[mtPermission] ([description] ,[display] ,[seq] ,[sub_seq])
VALUES ('admin-changepassword','ADMIN_CHANGE_PASSWORD',100,300)
INSERT INTO [dbo].[mtPermission] ([description] ,[display] ,[seq] ,[sub_seq])
VALUES ('admin-setpassword','ADMIN_SET_PASSWORD',100,301)

INSERT INTO [dbo].[mtPermission] ([description] ,[display] ,[seq] ,[sub_seq])
VALUES ('admin-permission','PERMISSION',200,100)
INSERT INTO [dbo].[mtPermission] ([description] ,[display] ,[seq] ,[sub_seq])
VALUES ('admin-permissionlist','PERMISSION_LIST',200,101)



INSERT INTO [dbo].[mtPermission] ([description] ,[display] ,[seq] ,[sub_seq])
VALUES ('brand-index','BRAND_PAGE',1000,100)
INSERT INTO [dbo].[mtPermission] ([description] ,[display] ,[seq] ,[sub_seq])
VALUES ('brand-profile_read','BRAND_LIST',1000,110)
INSERT INTO [dbo].[mtPermission] ([description] ,[display] ,[seq] ,[sub_seq])
VALUES ('brand-create','BRAND_CREATE',1000,111)
INSERT INTO [dbo].[mtPermission] ([description] ,[display] ,[seq] ,[sub_seq])
VALUES ('brand-update','BRAND_UPDATE',1000,112)
INSERT INTO [dbo].[mtPermission] ([description] ,[display] ,[seq] ,[sub_seq])
VALUES ('brand-delete','BRAND_DELETE',1000,200)

INSERT INTO [dbo].[mtPermission] ([description] ,[display] ,[seq] ,[sub_seq])
VALUES ('transaction-index','TRANSACTION_PAGE',2000,100)
INSERT INTO [dbo].[mtPermission] ([description] ,[display] ,[seq] ,[sub_seq])
VALUES ('transaction-transaction_read','TRANSACTION_LIST',2000,110)
INSERT INTO [dbo].[mtPermission] ([description] ,[display] ,[seq] ,[sub_seq])
VALUES ('transaction-create','TRANSACTION_CREATE',2000,111)
INSERT INTO [dbo].[mtPermission] ([description] ,[display] ,[seq] ,[sub_seq])
VALUES ('transaction-update','TRANSACTION_UPDATE',2000,112)
INSERT INTO [dbo].[mtPermission] ([description] ,[display] ,[seq] ,[sub_seq])
VALUES ('transaction-delete','TRANSACTION_DELETE',2000,200)